/// 1. Familiar in the state channel pattern of Cardano development
///    - find current utxo validating
///    - check only 1 input and output from same address with updated datum
/// 3. Understand that the script might not be performed as imagined - starter can start with ending datum
/// 2. Can distinguish between: the smart contract updates the datum vs the script validate if datum is updated -> building early concept on cardano validator
